### ISSUE TITLE
Typo in the link to Zanini_2018 averages data

### ISSUE THREAD

**Issue by Jon-bioinfo** [iosonofabio/atlas_averages#1]
Typo in the link to Zanini_2018 averages data.

**Comment by iosonofabio** [comment]
Thanks, in the csv or on the webpage?

**Comment by Jon-bioinfo** [comment]
Webpage, missing an n in landmarks

**Comment by iosonofabio** [comment]
Thank you, updated:

https://northstaratlas.github.io/atlas_landmarks/

**Comment by iosonofabio** [comment]
ah there were several typos, well it's fixed now
